# Custom Language File for CSMP Launcher

[ejs.app]
title = "CSMP Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO CSMP"
welcomeDescription = "Welcome to the CSMP community Minecraft server. Join our modded server and explore a world of adventure, creativity, and community. We bring together players from all over to experience Minecraft like never before."
welcomeDescCTA = "You are just a few clicks away from CSMP."
